### ISSUE TITLE
Significant memory usage increasing for lots of messages or long-time subscription

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#175] opened 2017-11-14 06:13 UTC
For publishers, neither lots of messages nor long time publishing will raise significant memory usage increase.

For subscriptions, lots of messages or long time publishing will raise a significant memory usage increase.
See the following tables:

| messages | time | publisher memory rising | subscription memory rising |
| --- | --- | --- | --- |
| 10k | about 100s | 0.29% | 0.27% |
| 100k | about 1000s | 0.43% | 6.5% |
| 86389 (1s interval) |  24 hours | 0.15% | 15.51% |

Not sure if there is memory leak for the subscription.

**Comment by minggangw** [comment] 2017-11-16 08:41
It seems that the rising of memory usage is irrelevant to the count of messages the subscription has received, but proportional to the duration of running.

**Comment by qiuzhong** [comment] 2017-11-17 02:12
| scenario | time | messags | interval | publisher memory rising | subscription memory rising |
| --- | --- | --- | --- | --- | --- |
| rclpy publisher <-> rclpy subscription| about 1000s | 100k | 10ms | 1.10% | 15.60% |
| rclnodejs publisher <-> rclpy subscription | 16 hours | 57592 | 1000ms | - | 14.66% |

**Comment by minggangw** [comment] 2017-11-17 03:23
From the statistics, the rclpy client as a subscription has an approximate increasement of memory usage compared with rclnodejs. I am going to retest the same use case. If I get the same result, the memory consumption may be caused by the middle ware of ROS.

**Comment by Christywl** [comment] 2017-12-08 07:16
Using the latest ROS2 and rclnodejs, I also find this issue for publisher/subscription and client/service:

| Scenario | Message | publisher memory rising | subscription memory rising |
| --- | --- | --- | --- |
| 24-hours-publisher.js/24-hours-subscription.js | 100k | 9.37% | 17.09% |



| Scenario | Client Increasing Rate | Service Increasing Rate |
| --- | --- | --- |
| one-hours-client.js/one-hours-service.js | 0.17% | 5.07% |
| 24-hours-client.js/24-hours-service.js | 0.24% | **24.95%** |

**Comment by minggangw** [comment] 2017-12-11 02:28
Did you test this case on [Ardent Apalone](https://github.com/ros2/ros2/wiki/Release-Ardent-Apalone)?

**Comment by Christywl** [comment] 2017-12-11 02:55
Before that, I run the tests based on https://github.com/ros2/ros2/commit/b12ebdc199c5c41f5ddfda9dabf0abc21a936d6b

**Comment by minggangw** [comment] 2018-04-16 03:18
Now we have a type of endurance in the [benchmark](https://github.com/RobotWebTools/rclnodejs/tree/develop/benchmark) tests, I think we can utilize those to investigate this potential issue.

**Comment by hanyia** [comment] 2018-05-10 09:04
scenario | execution time | messags | interval | publisher memory rising | subscription memory rising
-- | -- | -- | -- | -- | --
subscription-endurance-test.js/publisher-endurnance-test.js | 19 hours | 3600000K | 10ms | 45.11% | 31.32%

**Comment by hanyia** [comment] 2018-05-11 05:30
We test subscription/publisher get below result:

scenario | execution time | message | interval | publisher memory rising | subscription memory rising
-- | -- | -- | -- | -- | --
subscription/publisher | 19 hours | 3600000k | 10ms | 45.11% | 31.32%

**Comment by minggangw** [comment] 2018-07-23 10:29
Hi @qiuzhong as PR #385， which fixed issue #381， may resolve this old issue too, would you please retest the case mentioned in this thread and see whether there is still a rising of memory consumption.

If we verify the problem doesn't appear again, then we can close it :smile:

Thanks!

**Comment by qiuzhong** [comment] 2018-07-24 01:40
@minggangw , surely I'll make a test and report it based on the new fix.

**Comment by minggangw** [comment] 2018-07-24 03:08
Thanks a lot!

**Comment by minggangw** [comment] 2018-07-26 10:01
Hi @qiuzhong any updates?

**Comment by qiuzhong** [comment] 2018-07-27 03:07
@minggangw , tried with message `std_msgs/msg/Header`. Here is the report:

| messages | time | publisher memory rising | subscription memory rising |
| --- | --- | --- | --- |
| 10k | about 100s | 0.11% | 0.09% |
| 100k | about 1000s | 1.35% | 1.08% |
| 86389 (1s interval) |  24 hours | 0.11% | 0.41% |

From this report, we can see the memory consumption has reduced very significantly.

**Comment by minggangw** [comment] 2018-07-27 03:29
Great, thanks for your effort @qiuzhong, I think we can close this issue now due to #385. Please reopen it if the problem can reproduce in the future.

**Closed as completed by minggangw** 2018-07-27 03:29 UTC
