### ISSUE TITLE
NodeJS version

### ISSUE THREAD

**Issue by lukaszmitka** [RobotWebTools/rclnodejs#553] opened 2020-01-21 10:39 UTC
I was trying to use rclnodejs with NodeJS v8.17 and it ended up in segmentation fault when running examples. Upgrading to v10.18 solved the issue.
I am working on Ubuntu 18.04 and ROS Dashing Patch 4.
README states that NodeJS versions between 6.10 - 10.99 are compatible, did I do something wrong, or  README should be updated?

**Comment by minggangw** [comment] 2020-01-21 14:15
The minimum version of NodeJS, which is v6.10 on Ubuntu 16.04 LTS, was once verified on a very old release of ROS2 (maybe on the first stable release about 2 years ago). After that, we haven't verified it again, so it may become imprecise.

Would you please help to paste the core dump? If it's caused by the incompatibility of Node.js, we are going to update the README accordingly, thanks!

**Comment by lukaszmitka** [comment] 2020-01-22 09:44
I have run the example subscriber with valgrind: `valgrind -v --track-origins=yes node example/subscription-example.js`
The output is: https://rclnodejs-segfault.s3.eu-central-1.amazonaws.com/valgrind.log

And the core dump from running `node example/subscription-example.js`: https://rclnodejs-segfault.s3.eu-central-1.amazonaws.com/core_dump

**Comment by minggangw** [comment] 2020-01-22 13:58
Thanks, I am going to reproduce it locally and find any useful information, then get back.

**Comment by minggangw** [comment] 2020-01-27 15:21
I did some investigation locally and found that the crash happens when calling rcl_init_options_init() from librcl.so. It seems that it's not a problem caused by Node.js, I will dig deeper.

**Comment by minggangw** [comment] 2022-06-20 03:00
The supported nodejs versions are
https://github.com/RobotWebTools/rclnodejs/blob/f50e2b895c0a3129d8a85c6066cb17a031f94349/package.json#L92
Close this issue, please re-open it if you still have questions, thanks!

**Closed as completed by minggangw** 2022-06-20 03:00 UTC
Labels: bug, more-information-needed
